@extends('layouts.app')

@section('content')
<div class="phero"><div class="wrap">
<div class="crumb"><a href="{{ route('home') }}">Home</a> <span style="color:var(--rule)">/</span> Platform</div><span class="ey">Platform</span><h1>The workspace your institution runs on.</h1><p class="lead">The pipeline, one file's journey, the task library, deployment and integrations — on a single page.</p>
</div></div>

<section><div class="wrap"><div class="sh rv"><span class="ey">The Pipeline</span><h2>Five steps. Watch it move.</h2></div><div class="flow rv"><div class="fline"><span class="fpulse"></span></div><div class="fsteps"><div class="fstep" data-cap="Paper, scans and legacy systems become structured, searchable records."><div class="fdot">I</div><b>Capture</b><span>OCR &amp; ingest</span></div><div class="fstep" data-cap="Fields, entities and relationships mapped — with human review queues."><div class="fdot">II</div><b>Understand</b><span>Classify &amp; extract</span></div><div class="fstep" data-cap="Answers only from records that role may see, cited to file and page."><div class="fdot">III</div><b>Ground</b><span>Cited retrieval</span></div><div class="fstep" data-cap="Documents assembled from your precedent — whatever the workflow requires."><div class="fdot">IV</div><b>Draft</b><span>Ved at work</span></div><div class="fstep" data-cap="A person reviews and signs. The immutable trail records everything."><div class="fdot">V</div><b>Approve</b><span>Human gate</span></div></div><div class="fcap"></div></div><div class="statrow"><div class="stat rv"><div class="v" data-to="7">0</div><div class="k">Ways to work: ask, search, compare, summarise, extract, draft, trace</div></div><div class="stat rv"><div class="v" data-to="3">0</div><div class="k">Deployment models</div></div><div class="stat rv"><div class="v" data-to="100">0<small>%</small></div><div class="k">Claims carrying citations</div></div><div class="stat rv"><div class="v" data-to="0">0</div><div class="k">Records leaving your perimeter</div></div></div></div></section>

<section class="band-tint"><div class="wrap"><div class="sh rv"><span class="ey">One File's Journey</span><h2>From shelf to signature.</h2><p class="lead">Follow a single record through the system — press play, or take the controls.</p></div><div class="scenes rv"><div class="sc-bars"><div class="sc-bar"><i></i></div><div class="sc-bar"><i></i></div><div class="sc-bar"><i></i></div><div class="sc-bar"><i></i></div><div class="sc-bar"><i></i></div></div><div class="sc-slide"><div class="sc-tag">SCENE 01 · THE ARCHIVE</div><div class="sc-title">A record room, decades deep.</div><p class="sc-text">Physical files, scans and siloed systems — memory, unreadable at scale.</p></div><div class="sc-slide"><div class="sc-tag">SCENE 02 · CAPTURE</div><div class="sc-title">Every page becomes data.</div><p class="sc-text">Layout-aware OCR digitises tables, stamps and forms; classification files each record.</p></div><div class="sc-slide"><div class="sc-tag">SCENE 03 · GROUND</div><div class="sc-title">Ask. Get cited answers.</div><p class="sc-text">Retrieval runs only over records your role may see — every claim cited.</p></div><div class="sc-slide"><div class="sc-tag">SCENE 04 · DRAFT</div><div class="sc-title">Ved writes the document.</div><p class="sc-text">An office order, a tender reply, an RTI response — from your own precedent.</p></div><div class="sc-slide"><div class="sc-tag">SCENE 05 · SIGN</div><div class="sc-title">A human approves. Always.</div><p class="sc-text">The officer signs; the audit trail records every step. Ved never dispatches.</p></div><div class="sc-play">▸ Auto-playing — tap the bars to jump</div></div></div></section>

<section><div class="wrap"><div class="sh rv"><span class="ey">Ved's Task Library</span><h2>Shaped by your workflow — not a fixed menu.</h2><p class="lead">These are common configurations. If your process demands an output, Ved is configured to produce it.</p></div><div class="grid g3 stg"><div class="card"><span class="n">DRAFT</span><h3>Orders &amp; Memos</h3><p>From precedent, in your house format.</p></div><div class="card"><span class="n">DRAFT</span><h3>Charters &amp; SOPs</h3><p>Structured, template-true, cited.</p></div><div class="card"><span class="n">DRAFT</span><h3>Tender &amp; RTI Replies</h3><p>Scope-matched; exemption-flagged; redacted.</p></div><div class="card"><span class="n">ANALYSE</span><h3>Summaries &amp; Comparisons</h3><p>Files, policies, timelines — grounded.</p></div><div class="card"><span class="n">EXTRACT</span><h3>Registers &amp; Reports</h3><p>Structured data lifted into the formats you file.</p></div><div class="card"><span class="n">EXTEND</span><h3>Your Workflow's Demands</h3><p>Defined during configuration, per department and role.</p><a class="go" href="{{ route('contact') }}#brief" style="display:block">Discuss yours →</a></div></div></div></section>

<section class="band-tint"><div class="wrap"><div class="sh rv"><span class="ey">Deployment</span><h2>Your data never crosses this line.</h2></div><div class="perim2 rv"><span class="tag">● Your perimeter · zero data egress</span><div id="flowp" style="position:absolute;inset:0;pointer-events:none"></div><div class="grid g3" style="position:relative;z-index:2"><div class="card" style="text-align:center"><div class="n">◈ ON-PREMISES</div><h3 style="margin-top:8px">Full Control</h3><p>Your hardware, your data centre.</p></div><div class="card" style="text-align:center"><div class="n">◈ SOVEREIGN CLOUD</div><h3 style="margin-top:8px">Your Environment</h3><p>Approved government or private cloud.</p></div><div class="card" style="text-align:center"><div class="n">◈ AIR-GAPPED</div><h3 style="margin-top:8px">Isolated</h3><p>No external connectivity at all.</p></div></div></div></div></section>

<section><div class="wrap"><div class="sh rv"><span class="ey">Integrations</span><h2>Everything flows to the core. Nothing flows out.</h2></div><div class="intg rv"><svg viewBox="0 0 820 260" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Integration diagram: capture, records, enterprise, identity, permissions and connectors all flow into the VedVault core, which grounds and governs — nothing flows out.">
<defs><path id="p1" d="M150,50 C300,50 350,120 410,130"/><path id="p2" d="M410,50 C410,90 410,100 410,130"/><path id="p3" d="M670,50 C520,50 470,120 410,130"/>
<path id="p4" d="M150,210 C300,210 350,140 410,130"/><path id="p5" d="M410,210 C410,170 410,150 410,130"/><path id="p6" d="M670,210 C520,210 470,140 410,130"/></defs>
<g stroke="rgba(201,162,39,.4)" fill="none" stroke-width="1.2"><use href="#p1"/><use href="#p2"/><use href="#p3"/><use href="#p4"/><use href="#p5"/><use href="#p6"/></g>
<g fill="#D9B44A"><circle r="3.5"><animateMotion dur="2.6s" repeatCount="indefinite"><mpath href="#p1"/></animateMotion></circle>
<circle r="3.5"><animateMotion dur="2.2s" repeatCount="indefinite"><mpath href="#p2"/></animateMotion></circle>
<circle r="3.5"><animateMotion dur="3s" repeatCount="indefinite"><mpath href="#p3"/></animateMotion></circle>
<circle r="3.5"><animateMotion dur="2.8s" repeatCount="indefinite"><mpath href="#p4"/></animateMotion></circle>
<circle r="3.5"><animateMotion dur="2.4s" repeatCount="indefinite"><mpath href="#p5"/></animateMotion></circle>
<circle r="3.5"><animateMotion dur="3.2s" repeatCount="indefinite"><mpath href="#p6"/></animateMotion></circle></g>
<g text-anchor="middle">
<g transform="translate(150,50)"><rect x="-85" y="-20" width="170" height="40" rx="20" fill="none" stroke="#8A8471"/><text class="ntxt" y="-1">Scanners &amp; drives</text><text class="nsub" y="12">CAPTURE</text></g>
<g transform="translate(410,50)"><rect x="-85" y="-20" width="170" height="40" rx="20" fill="none" stroke="#8A8471"/><text class="ntxt" y="-1">DMS &amp; archives</text><text class="nsub" y="12">RECORDS</text></g>
<g transform="translate(670,50)"><rect x="-85" y="-20" width="170" height="40" rx="20" fill="none" stroke="#8A8471"/><text class="ntxt" y="-1">ERP &amp; case systems</text><text class="nsub" y="12">ENTERPRISE</text></g>
<g transform="translate(150,210)"><rect x="-85" y="-20" width="170" height="40" rx="20" fill="none" stroke="#8A8471"/><text class="ntxt" y="-1">SSO &amp; directory</text><text class="nsub" y="12">IDENTITY</text></g>
<g transform="translate(410,210)"><rect x="-90" y="-20" width="180" height="40" rx="20" fill="none" stroke="#8A8471"/><text class="ntxt" y="-1">Role-based access</text><text class="nsub" y="12">PERMISSIONS</text></g>
<g transform="translate(670,210)"><rect x="-85" y="-20" width="170" height="40" rx="20" fill="none" stroke="#8A8471"/><text class="ntxt" y="-1">APIs &amp; connectors</text><text class="nsub" y="12">EXTEND</text></g>
<g transform="translate(410,130)"><rect x="-72" y="-26" width="144" height="52" rx="10" fill="#0B1D33" stroke="#C9A227"/><text y="-3" style="font-family:IBM Plex Mono,monospace;font-size:12px;fill:#F5EFE0;font-weight:700">VedVault Core</text><text class="nsub" y="13">GROUND · GOVERN</text></g>
</g></svg></div></div></section>

@include('partials.cta')
@endsection
